run_pre_inject_flickr8k_googlenet:
	python test.py --dataset-name flickr8k \
				   --cnn-name googlenet \
				   --model-name pre-inject \
				   --batch-size 256 \
				   --embed-size 300 \
				   --eval-every 10 \
				   --num-iterations 400 \
				   --learning-rate 0.001 \
				   --plot-name example
